version: '3'
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/root/.grafana
    restart: always
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.4
    container_name: influxdb
    volumes:
      - ./influxdbv2:/root/.influxdbv2
    ports:
      - "8086:8086"
    restart: always
volumes:
  influxdbv2:
  grafana: